metadata.format.version = "1.1"

[versions]

velocity = "3.4.0-SNAPSHOT"
adventure = "4.26.1"

blossom = "2.2.0"
shadow = "8.1.1"
runtask = "3.0.2"

miniplaceholders = "3.1.0"
spark = "0.1-SNAPSHOT"

[libraries]

miniplaceholders = { group = "io.github.miniplaceholders", name = "miniplaceholders-api", version.ref = "miniplaceholders" }
spark = { group = "me.lucko", name = "spark-api", version.ref = "spark" }
adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventure-minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure" }

[plugins]

blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
runvelocity = { id = "xyz.jpenilla.run-velocity", version.ref = "runtask" }

